#!/usr/bin/env python3

import os, argparse, ffmpeg, time
from pymediainfo import MediaInfo
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor


DIRECTORY = Path().cwd()
VIDEO_EXTENSIONS = [".mp4", ".mkv", ".avi", ".mov", ".flv", ".wmv"]
COLOR_RED = "\033[91m"
COLOR_RESET = "\033[0m"

parser = argparse.ArgumentParser(description="Organize video files into folders based on metadata or filename.")
parser.add_argument("-d", "--dry", action="store_true", help="Dry run mode. No files will be renamed or removed.")
parser.add_argument("-v", "--verbose", action="store_true", help="Verbose mode, maximum logs.")
parser.add_argument("-s", "--seconds", type=int, default=20, help="Minimum duration (in seconds) for video files to keep.")
parser.add_argument("-c", "--compression", type=int, default=25, help="Compression level for ffmpeg (lower is better quality, default is 25. range 0-51).")
args = parser.parse_args()
Min_duration_sec = args.seconds
compression_level = args.compression
target_fps = 60

untouched_files = []
removed_files = []
tagged_for_compression = []

def convert_video(file, compression_level):
    if not os.path.exists(file):
        print(f"Input file {file} does not exist.")
        return False

    output_file = file.with_stem(f"{file.stem}_compressed")
    try:
        if not args.dry:
            ffmpeg.input(str(file)).output(
                str(output_file), 
                vcodec='libx264', 
                crf=compression_level,
                loglevel='error',
                r=target_fps
                ).overwrite_output().run()
            print(f"Before and after compression: {os.path.getsize(file) / (1024 * 1024):.2f} MB/{os.path.getsize(output_file) / (1024 * 1024):.2f} MB")
        return True
        
    except ffmpeg.Error as e:
        print(f"An error occurred during compression: {e}")
        return False

def compress_tagged_files():
    for i,file in enumerate(tagged_for_compression, start=1):
        print(f"Compression of file {i}/{len(tagged_for_compression)}")
        if convert_video(file,compression_level):
            removed_files.append(file)

def recognize_name(p):
    file_name = p.name
    if file_name.startswith("GH"):
        if args.verbose:
            print("Processing GOPRO file: ", file_name)
        rename_file_metadata(file_name)
    elif file_name.startswith("DJI"):
        if args.verbose:
            print("Processing DJI file: ", file_name)
        rename_file_name(file_name)
    else:
        if p not in untouched_files:
            untouched_files.append(p)
    
def handle_file_dur(p):
    try:
        duration_ms = MediaInfo.parse(p).tracks[0].duration
    except Exception as e:
        print(f"Could not read metadata for {p.name}: {e}")
        return False

    duration_sec = duration_ms / 1000
    if duration_sec < Min_duration_sec:
        print(f"File {p.name} is too short: removing..")
        removed_files.append(p)
        return False
    return True

def iterate_over_single(single_file):
    if handle_file_dur(single_file):
        recognize_name(single_file)

def rename_file_name(file_name):
    #only for DJI files
    stripped_name_date = file_name[4:12]
    stripped_name_flight = file_name[19:23]
    date_DD_MM_YY = stripped_name_date[6:8] + "_" + stripped_name_date[4:6] + "_" + stripped_name_date[0:4]
    
    folder = DIRECTORY / date_DD_MM_YY
    if not folder.exists():
        if args.verbose:
            print("Creating folder: ", folder)
        if not args.dry:
            folder.mkdir()

    new_file_name = folder / (stripped_name_flight + Path(file_name).suffix)
    if new_file_name.exists():
        print(f"File {new_file_name} already exists. Skipping..")
        return
    if args.verbose:
        print("Renaming file to: ", new_file_name)
    if not args.dry:
        os.rename(DIRECTORY / file_name, new_file_name)

    tagged_for_compression.append(new_file_name)

def rename_file_metadata(file_name):
    #only for GOPRO files
    info = MediaInfo.parse(DIRECTORY / file_name)
    stripped_name_date = info.tracks[0].encoded_date[0:10]
    stripped_name_date = stripped_name_date.replace("-", "")
    date_DD_MM_YY = stripped_name_date[6:8] + "_" + stripped_name_date[4:6] + "_" + stripped_name_date[0:4]
    folder = DIRECTORY / date_DD_MM_YY
    if not folder.exists():
        if args.verbose:
            print("Creating folder: ", folder)
        if not args.dry:
            folder.mkdir()

    new_file_name = folder / (file_name)
    if args.verbose:
        print("Renaming file to: ", new_file_name)
    if not args.dry:
        os.rename(DIRECTORY / file_name, new_file_name)

    tagged_for_compression.append(new_file_name)

def sort_organize():
    if args.verbose:
        print("Working in directory: ", DIRECTORY)
    for file in list(DIRECTORY.iterdir()):
        if file.suffix.lower() in VIDEO_EXTENSIONS:
            iterate_over_single(file)
        else:
            untouched_files.append(file.name)

    if args.verbose:
        print("Untouched files or directories: ", untouched_files)        


def cleanup():
    if not removed_files:
        return
    print(f"\n{COLOR_RED} *REMOVING THESE FILES* {COLOR_RESET}", [f.name for f in removed_files])
    print("Are your sure? (y/N)")
    answer = input().strip()
    if answer.lower() != "y":
        print("Aborting..")
        return
    for file in removed_files:
        try:
            if not args.dry:
                os.remove(file)
        except Exception as e:
            print(f"Error removing file {file}: {e}")
    print("Files removed successfully.")
    
if __name__ == "__main__":
    print("Program version: 0.2")
    print("This script will organize your video files into folders based on their metadata or filename.")
    print(f"It will also remove files that are shorter than {Min_duration_sec} seconds.")
    start = time.time()
    sort_organize()
    compress_tagged_files()
    cleanup()
    end = time.time()
    print(f"Took: {end-start:.2f} seconds")
    print("*** DONE ***")

